In [7]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = {
    "Name": ["Amit", "Ravi", "Priya", "Neha"],
    "Age": [22, 30, 45, 35],
    "Salary": [25000, 50000, 75000, 60000],
    "Department": ["HR", "IT", "Finance", "HR"],
}
df = pd.DataFrame(data)
df

    Name  Age  Salary Department
0   Amit   22   25000         HR
1   Ravi   30   50000         IT
2  Priya   45   75000    Finance
3   Neha   35   60000         HR

In [4]:
df["AnnualSalary"] = df["Salary"] * 12
df

    Name  Age  Salary Department  AnnualSalary
0   Amit   22   25000         HR        300000
1   Ravi   30   50000         IT        600000
2  Priya   45   75000    Finance        900000
3   Neha   35   60000         HR        720000

In [5]:
df["AgeGroup"] = pd.cut(
    df["Age"], bins=[0, 25, 40, 100], labels=["Young", "Adult", "Senior"]
)
df

    Name  Age  Salary Department  AnnualSalary AgeGroup
0   Amit   22   25000         HR        300000    Young
1   Ravi   30   50000         IT        600000    Adult
2  Priya   45   75000    Finance        900000   Senior
3   Neha   35   60000         HR        720000    Adult

In [6]:
df = pd.get_dummies(df, columns=["Department"])
df

,Name,Age,Salary,AnnualSalary,AgeGroup,Department_Finance,Department_HR,Department_IT
0,Amit,22,25000,300000,Young,False,True,False
1,Ravi,30,50000,600000,Adult,False,False,True
2,Priya,45,75000,900000,Senior,True,False,False
3,Neha,35,60000,720000,Adult,False,True,False

In [8]:
scaler = MinMaxScaler()
df["Salary"] = scaler.fit_transform(df[["Salary"]])
df

,Name,Age,Salary,AnnualSalary,AgeGroup,Department_Finance,Department_HR,Department_IT
0,Amit,22,0.0,300000,Young,False,True,False
1,Ravi,30,0.5,600000,Adult,False,False,True
2,Priya,45,1.0,900000,Senior,True,False,False
3,Neha,35,0.7,720000,Adult,False,True,False