In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = {"Age": [20, 25, 35], "Salary": [20000, 40000, 60000]}
df = pd.DataFrame(data)
df

   Age  Salary
0   20   20000
1   25   40000
2   35   60000

In [3]:
df["Annual Salary"] = df["Salary"]*12
df

   Age  Salary  Annual Salary
0   20   20000         240000
1   25   40000         480000
2   35   60000         720000

In [4]:
df["Age Group"] = pd.cut(
    df["Age"],
    bins=2,
    labels=["Young Adult", "Adult"]
)
df

   Age  Salary  Annual Salary    Age Group
0   20   20000         240000  Young Adult
1   25   40000         480000  Young Adult
2   35   60000         720000        Adult

In [8]:
scaler = MinMaxScaler()
df["Salary Normalized"] = scaler.fit_transform(df[["Salary"]])
df

   Age  Salary  Annual Salary    Age Group  Salary Normalized
0   20   20000         240000  Young Adult                0.0
1   25   40000         480000  Young Adult                0.5
2   35   60000         720000        Adult                1.0